# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('c_time', models.DateField()),
                ('m_time', models.DateField()),
                ('phone', models.CharField(max_length=20, null=True)),
                ('mail_address', models.CharField(max_length=50, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Depart')),
                ('usergroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workid', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=255)),
                ('bind_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bind_user', to='app01.User')),
                ('own_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_user', to='app01.User')),
            ],
        ),
    ]
