# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20170615_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='own_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_user', to='app01.User', verbose_name='\u7ed1\u5b9a\u7528\u6237'),
        ),
    ]
